[lint]
# 1. Enable flake8-bugbear (`B`) rules, in addition to the defaults.
select = ["E4", "E7", "E9", "F", "B"]

# 2. Avoid enforcing line-length violations (`E501`)
ignore = ["E501"]

# 3. Avoid trying to fix flake8-bugbear (`B`) violations.
unfixable = ["B"]


[lint.flake8-import-conventions]
# Declare the banned `from` imports.
banned-from = ["os.path", "numpy", "pandas", "numbers.util"]



[format]
# 5. Use single quotes for non-triple-quoted strings.
quote-style = "single"